steps:
  - target: body
    placement: center
    title: '<div style="font-size: 24px; color: var(--grape_500)">Welcome to Label Studio!</div>'
    content: '<div style="width: 100%">Seems like you have no projects yet. Lets create one together to label images!</div>'
