# Generated by Django 5.1.5 on 2025-02-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_auto_20241107_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("annotator", "Annotator"),
                    ("approver", "Approver"),
                    ("admin", "Admin"),
                ],
                default="annotator",
                help_text="Project member role",
                max_length=50,
                verbose_name="role",
            ),
        ),
    ]
