name: Algolia Indexer for Label Studio Docs

on:
  push:
    branches: ["develop"]
    paths:
      - "docs/**"
      - ".github/workflows/algolia-crawler-ls-docs.yml"
  pull_request:
    branches:
      - develop

jobs:
  algolia_indexer:
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: "M7RXTHKYPM"
      API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      INDEX_NAME: "labelstudiodocs"
      CONFIG: >
        {
          "index_name": "labelstudiodocs",
          "stop_urls": [], 
          "selectors_exclude": [".home-page-index"], 
          "start_urls": [
            {
              "url": "https://labelstud.io/guide",
              "selectors_key": "docs"
              
            },
            {
              "url": "https://labelstud.io/templates",
              "selectors_key": "docs"
              
            },
            {
              "url": "https://labelstud.io/tags",
              "selectors_key": "docs"
              
            },
            {
              "url": "https://labelstud.io/blog/openai-structured-outputs-with-label-studio/**",
              "selectors_key": "docs"
            }
          ],
          "sitemap_urls": ["https://labelstud.io/sitemap-tutorials.xml"],
          "selectors": {
            "docs": {
              "lvl0": ".content h1, .ResourcesBannerHeading",
              "lvl1": ".content h2, .ResourcesContent h2",
              "lvl2": ".content h3, .ResourcesContent h3",
              "lvl3": ".content h4, .ResourcesContent h4",
              "lvl4": ".content h5, .ResourcesContent h5",
              "lvl5": ".content h6, .ResourcesContent h6", 
              "content": ".content-markdown > *"
            },
            "default": {
              "lvl0": ".BlogTitle",
              "lvl1": ".ResourcesContent h1, .ResourcesContent h2",
              "lvl2": ".ResourcesContent h3",
              "lvl3": ".ResourcesContent h4",
              "lvl4": ".ResourcesContent h5",
              "lvl5": ".ResourcesContent h6", 
              "content": ".ResourcesContent > .Text"
            }
          }
        }
    name: Index Algolia
    steps:
      - name: Algolia Docsearch Action
        id: algolia
        uses: adapttive/algolia-docsearch-action@1.1.1
