name: Algolia Indexer

on:
  push:
    branches: [ 'ht/add-new-theme' ]
    paths:
      - 'docs/**'

jobs:
  algolia_indexer:
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: "M7RXTHKYPM"
      API_KEY: {{ALGOLIA_ADMIN_API_KEY}}
      INDEX_NAME: "ghaction"
      CONFIG: '{"index_name": "ghaction","start_urls": ["https://label-studio-docs-new-theme-enterpris.netlify.app/guide"],"selectors": {"lvl0": ".content h1, .ResourcesBannerHeading","lvl1": ".content h2, .ResourcesContent h2","lvl2": ".content h3, .ResourcesContent h3","lvl3": ".content h4, .ResourcesContent h4","lvl4": ".content h5, .ResourcesContent h5","lvl5": ".content h6, .ResourcesContent h6"}}'
    name: Index Algolia
    steps:
    - name: Algolia Docsearch Action
      id: algolia
      uses:  adapttive/algolia-docsearch-action@1.1.1