name: Algolia Indexer for Label Studio Docs

on:
  push:
    branches: ["develop"]
    paths:
      - "docs/**"
      - ".github/workflows/algolia-crawler-ls-docs.yml"
  pull_request:
    branches:
      - develop

jobs:
  algolia_indexer:
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: "HELLEDAKPT"
      API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      INDEX_NAME: "ghactionls"
      CONFIG: >
        {"index_name": "ghactionls",
        "stop_urls": [], 
        "selectors_exclude": [".home-page-index"], 
        "start_urls": ["https://labelstud.io/guide", "https://labelstud.io/templates", "https://labelstud.io/tags", "https://labelstud.io/blog/categories/tutorials/"],
        "selectors": {
        "lvl0": ".content h1, .ResourcesBannerHeading, .BlogTitle",
        "lvl1": ".content h2, .ResourcesContent h2",
        "lvl2": ".content h3, .ResourcesContent h3",
        "lvl3": ".content h4, .ResourcesContent h4",
        "lvl4": ".content h5, .ResourcesContent h5",
        "lvl5": ".content h6, .ResourcesContent h6", 
        "content": ".content-markdown > *"
        }}
    name: Index Algolia
    steps:
      - name: Algolia Docsearch Action
        id: algolia
        uses: adapttive/algolia-docsearch-action@1.1.1
