name: "Docker build & push"

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      branch_name:
        required: true
        type: string
    outputs:
      image_version:
        description: "Docker tag"
        value: ${{ jobs.prepare_build.outputs.image_version }}

env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  IMAGE_NAME: "${{ vars.DOCKERHUB_ORG }}/label-studio"
  DOCKER_IMAGE_TAG_CHECK_NAME: "Docker image tag"
  LAUNCHDARKLY_DOWNLOAD_PATH: "label_studio/feature_flags.json"
  VERSION_FILE: "label_studio/core/version_.py"

jobs:
  prepare_build:
    name: "Prepare for build"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.version.outputs.image_version }}
      pretty_branch_name: ${{ steps.version.outputs.pretty_branch_name }}
      sha: ${{ steps.version.outputs.sha }}
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ref: ${{ inputs.sha }}
          fetch-depth: 0

      - name: Calculate version
        id: version
        env:
          BRANCH_NAME: ${{ inputs.branch_name }}
        run: |
          set -x
          sha="$(git rev-parse HEAD)"
          echo "sha=$sha" >> $GITHUB_OUTPUT
          regexp='^ls-release\/(.*)$'; 
          if [[ "$BRANCH_NAME" =~ $regexp ]]; then
            image_version="${BASH_REMATCH[1]}rc${sha}"
          else
            image_version=$BRANCH_NAME
          fi
          echo "image_version=${image_version}" >> $GITHUB_OUTPUT
          echo "ubi_image_version=ubi_${image_version}" >> $GITHUB_OUTPUT
          
          pretty_branch_name="$(echo -n "${BRANCH_NAME#refs/heads/}" | sed 's#/#-#g' | sed 's#_#-#g'| sed 's#\.#-#g' | tr '[:upper:]' '[:lower:]')"
          echo "pretty_branch_name=$pretty_branch_name" >> $GITHUB_OUTPUT
          current_time="$(date +'%Y%m%d.%H%M%S')"
          branch="-${pretty_branch_name}"
          short_sha="$(git rev-parse --short HEAD)"
          long_sha="$(git rev-parse HEAD)"
          echo "sha=$long_sha" >> $GITHUB_OUTPUT
          short_sha_length="$(echo $short_sha | awk '{print length}')"
          current_time_length="$(echo $current_time | awk '{print length}')"
          version="${current_time}$(echo $branch | cut -c1-$((50 - short_sha_length - current_time_length)))-${short_sha}"
          echo "build_version=$version" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create version_.py
        env:
          BRANCH_OVERRIDE: ${{ inputs.branch_name }}
          VERSION_OVERRIDE: ${{ steps.version.outputs.build_version }}
        run: |
          python3 $(pwd)/label_studio/core/version.py
          cat $(pwd)/${{ env.VERSION_FILE }}

      - name: Download LaunchDarkly Community config
        env:
          LAUNCHDARKLY_COMMUNITY_SDK_KEY: ${{ secrets.LAUNCHDARKLY_COMMUNITY_SDK_KEY }}
        run: |
          set -xeuo pipefail
          curl \
            --connect-timeout 30 \
            --retry 5 \
            --retry-delay 10 \
            -H "Authorization: $LAUNCHDARKLY_COMMUNITY_SDK_KEY" \
            "https://sdk.launchdarkly.com/sdk/latest-all" >"$LAUNCHDARKLY_DOWNLOAD_PATH"
          if [ "$(jq 'has("flags")' <<< cat $LAUNCHDARKLY_DOWNLOAD_PATH)" = "true" ]; then 
            echo "feature_flags.json is valid"
          else
            echo "feature_flags.json is invalid"
            cat $LAUNCHDARKLY_DOWNLOAD_PATH
            exit 1
          fi

      - uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: |
            ${{ env.LAUNCHDARKLY_DOWNLOAD_PATH }}
            ${{ env.VERSION_FILE }}

  build_docker_images:
    name: "Build docker images"
    timeout-minutes: 60
    needs: prepare_build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: macos-latest-xlarge
            platform: linux/arm64
    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ref: ${{ inputs.sha }}

      - uses: actions/download-artifact@v3
        with:
          name: build-info

      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        uses: crazy-max/ghaction-setup-docker@v2
        env:
          COLIMA_START_ARGS: --cpu 4 --memory 8 --disk 10 --arch aarch64 --vm-type=vz --verbose

      - name: debug logs
        if: always()
        run: cat /Users/runner/.colima/_lima/colima/ha.stderr.log

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ needs.prepare_build.outputs.image_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  github_check:
    name: "Github check"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs:
      - prepare_build
      - build_docker_images
    steps:
      - name: Create Docker image tag Check
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const details = {
              "branch": "${{ inputs.branch_name }}",
              "pretty_branch_name": "${{ needs.prepare_build.outputs.pretty_branch_name }}",
              "image_version": "${{ needs.prepare_build.outputs.image_version }}",
              "sha": "${{ needs.prepare_build.outputs.sha }}"
            }
            const { data: check } = await github.rest.checks.create({
              owner,
              repo,
              name: '${{ env.DOCKER_IMAGE_TAG_CHECK_NAME }}',
              head_sha: '${{ needs.prepare_build.outputs.sha }}',
              status: 'in_progress',
              output: {
                title: '${{ env.DOCKER_IMAGE_TAG_CHECK_NAME }}',
                summary: JSON.stringify(details)
              }
            });
            await github.rest.checks.update({
              owner,
              repo,
              check_run_id: check.id,
              status: 'completed',
              conclusion: 'success'
            });
