name: Check for broken links

on:
  pull_request:
    branches: ["develop"]
    paths:
      - "docs/**"
      - ".github/workflows/link-check.yml"
  workflow_dispatch:

jobs:
  check_links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Netlify Deploy Preview URL
        run: |
          PREVIEW_URL="https://deploy-preview-${{ github.event.pull_request.number }}--label-studio-docs-new-theme.netlify.app"
          echo "Preview URL is $PREVIEW_URL"
          echo "PREVIEW_URL=$PREVIEW_URL" >> $GITHUB_ENV

      - name: Check for broken links
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          # Required:
          url: "https://deploy-preview-${{ github.event.pull_request.number }}--label-studio-docs-new-theme.netlify.app"
          honorRobotExclusions: false
          ignorePatterns: "github,google"
          recursiveLinks: true # Check all URLs on all reachable pages (could take a while)
      - name: Get the result
        run: echo "${{steps.link-report.outputs.result}}"
