name: Check for Broken Links

on:
  pull_request:
    branches: ["develop"]
    paths:
      - "docs/**"
      - ".github/workflows/link-check.yml"
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress docs/
