name: "Conda"

on:
  workflow_call:
    inputs:
      head_sha:
        required: true
        type: string

env:
  CACHE_NAME_PREFIX: v1
  PIP_VERSION: "20.2"

jobs:
  conda:
    name: Conda
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
        python-version: [ "3.10" ]
        include:
          - os: "ubuntu-latest"
            pip-cache-path: "~/.cache/pip"
          - os: "windows-latest"
            pip-cache-path: "~\\AppData\\Local\\pip\\Cache"

    steps:
      - uses: hmarr/debug-action@v2.1.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: ${{ inputs.head_sha }}

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test-environment


      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install Python dependencies
        run: |
          pdm sync -G test

      - name: Conda info
        shell: bash -el {0}
        run: |
          conda info
          conda list
