name: "ZenDesk: Close GitHub Issue on Zendesk Ticket Solved"

on:
  workflow_dispatch:
    inputs:
      client_payload:
        description: "Payload from Zendesk"
        required: true
        type: string

jobs:
  close_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3.0.0

      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GIT_PAT_HEIDI }}
          script: |
            const sanitizedClientPayloadRaw = context.payload.inputs.client_payload
              .trim()
              .replaceAll("\n", "\\n")
              .replaceAll("\r", "\\r");
            
            core.startGroup("Parsed payload");
            const payload = JSON.parse(sanitizedClientPayloadRaw);
            core.info(JSON.stringify(payload, null, 2));
            core.endGroup();

            // Extract issue details from the Zendesk external_id
            const parts = payload.ticket.external_id.split("/");
            const issue_number = parts[parts.length - 1];
            const issue_repo = parts[parts.length - 3];
            const issue_owner = parts[parts.length - 4];

            // Close the GitHub issue
            await github.rest.issues.update({
              owner: issue_owner,
              repo: issue_repo,
              issue_number: issue_number,
              state: "closed"
            });

            core.info(`GitHub issue #${issue_number} closed successfully.`);
